### ISSUE TITLE
White castling is broken

### ISSUE THREAD

**Issue by paramt** [williamjchen/terminalchess#1]
white castling kingside results in a white king on g1 and **black** rook on f1 - should be a white rook

**Comment by williamjchen** [comment]
CFBR

**Comment by williamjchen** [comment]
![image](https://github.com/williamjchen/terminalchess/assets/16550634/5abb5a60-8bc2-447f-a707-8b420485d0c2)
cannot reproduce @paramt

**Comment by paramt** [comment]
I was able to reproduce it again with these moves

e2e4 e7e5
g1f3 g8f6
f1d3 f8d6
e1g1

using 2 tabs in the same terminal

**Comment by paramt** [comment]
@williamjchen issue only exists on terminalchess.com, not when running this locally

**Comment by paramt** [comment]
i am not crazy 
![image](https://github.com/williamjchen/terminalchess/assets/23563074/8883ae76-217c-484f-815c-6222296f7e13)

**Comment by williamjchen** [comment]
it has been fixed!!!! ty king 
![image](https://github.com/williamjchen/terminalchess/assets/16550634/37d3c37e-3811-4617-ae36-0d140c68e62c)

**Comment by williamjchen** [comment]
also added promotions
